name: fluttergh
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  dio: ^4.0.6
  connectivity_plus: ^2.3.9
  dartz: ^0.10.1
  flutter_dotenv: ^5.0.2
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6+5
  flutter_svg: ^1.0.3
  equatable: ^2.0.5
  percent_indicator: ^4.0.1
  google_fonts: ^3.0.1
  bot_toast: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  # Code generation
  mobx_codegen: ^2.0.2
  modular_codegen: ^3.0.2
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/pictures/
